name: Lint & Build CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: macos-latest # ARM64

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js 22.11.x
              uses: actions/setup-node@v4
              with:
                  node-version: 22.11.x
            - name: Use Swift 6.1
              uses: swift-actions/setup-swift@v2
              with:
                  swift-version: 6.1.0
            - run: npm ci
            - run: npm run lint
            - run: npm run build
